
# Generated by Django 5.0.2 on 2024-09-18 15:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("test", models.BooleanField(default=False)),
                ("client_created_by", models.CharField(max_length=255, null=True)),
                (
                    "client_creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="client_creation_date",
                    ),
                ),
                ("client_ap_details", models.JSONField(blank=True, null=True)),
                (
                    "client_payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                            ("Due on receipt", "Due on receipt"),
                            ("null", "null"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "client_invoice_terms",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("potential lead", "Potential Lead"),
                            ("onboarded", "ONBOARDED"),
                        ],
                        default="active",
                        max_length=33,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ("-client_creation_date",),
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("ceipal_id", models.IntegerField(primary_key=True, serialize=False)),
                ("employee_number", models.CharField(max_length=50)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                (
                    "emptype_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("job_title", models.JSONField(blank=True, default=list, null=True)),
                ("email_id", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "workauthorization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "skill_details",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "employee_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=20, null=True)),
                ("emp_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "assigned_role",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillPayRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="Assign Role", max_length=500)),
                ("skill", models.JSONField()),
                (
                    "billrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "companyrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "marketrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("location", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "start_date",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="End Date"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("files", models.JSONField(default=list)),
                (
                    "contract_name",
                    models.CharField(default="Default Contract Name", max_length=255),
                ),
                ("end_type", models.CharField(default="", max_length=255)),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                            ("Due on receipt", "Due on receipt"),
                            ("null", "null"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("contract_end_type", models.CharField(default="", max_length=255)),
                ("contract_version", models.FloatField(default=1.0)),
                (
                    "contract_creation_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("contract_created_by", models.CharField(max_length=100, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contracts",
                        to="c2c_modules.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.CreateModel(
            name="Estimation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("market_cost", models.FloatField(blank=True, null=True)),
                ("market_price", models.FloatField(blank=True, null=True)),
                ("market_gm", models.FloatField(blank=True, null=True)),
                ("company_avg_cost", models.FloatField(blank=True, null=True)),
                ("company_avg_price", models.FloatField(blank=True, null=True)),
                ("company_avg_gm", models.FloatField(blank=True, null=True)),
                (
                    "contract_start_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "contract_end_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                ("resource", models.JSONField()),
                ("estimation_archived", models.BooleanField(default=False)),
                (
                    "billing",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_estimation",
                        to="c2c_modules.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("blob_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="c2c_modules.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("estimated_market_cost", models.FloatField(blank=True, null=True)),
                ("estimated_market_price", models.FloatField(blank=True, null=True)),
                (
                    "estimated_company_avg_cost",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "estimated_company_avg_price",
                    models.FloatField(blank=True, null=True),
                ),
                ("market_gm", models.FloatField(blank=True, null=True)),
                ("company_avg_gm", models.FloatField(blank=True, null=True)),
                ("final_offer_price", models.FloatField(blank=True, null=True)),
                (
                    "final_offer_gross_margin_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("final_offer_margin", models.FloatField(blank=True, null=True)),
                ("discount", models.FloatField(blank=True, null=True)),
                (
                    "pricing_creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="pricing_creation_date",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_pricing",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "estimation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_pricing",
                        to="c2c_modules.estimation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("purchase_order_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=20)),
                ("po_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "start_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                ("purchase_order_documents", models.JSONField(default=list)),
                (
                    "po_creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="po_creation_date",
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_po",
                        to="c2c_modules.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sow_Contract",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contractsow_name", models.CharField(max_length=255)),
                (
                    "total_contract_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "contractsow_creation_date",
                    models.DateField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="contractsow_creation_date",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                ("document", models.JSONField(default=list)),
                (
                    "payment_term_client",
                    models.CharField(default="Default Payment term", max_length=255),
                ),
                (
                    "payment_term_contract",
                    models.CharField(
                        choices=[
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                            ("Due on receipt", "Due on receipt"),
                            ("null", "null"),
                        ],
                        default="Net 30",
                        max_length=20,
                    ),
                ),
                ("contractsow_type", models.CharField(default="", max_length=255)),
                (
                    "doc_contract_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "doc_start_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Doc Start Date",
                    ),
                ),
                (
                    "doc_end_date",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Doc End Date",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contractsow",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "estimation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_contractsow",
                        to="c2c_modules.estimation",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_contractsow",
                        to="c2c_modules.pricing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sow_Contract",
                "verbose_name_plural": "Sow_Contracts",
            },
        ),
        migrations.CreateModel(
            name="Main_milestone",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "milestone_total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("milestones", models.JSONField()),
                (
                    "client_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "contract_sow_uuid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractsow_milestones",
                        to="c2c_modules.sow_contract",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                (
                    "c2c_invoice_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("c2c_invoice_type", models.CharField(max_length=50)),
                ("c2c_invoice_type_id", models.CharField(max_length=50)),
                (
                    "c2c_invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "c2c_old_invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                (
                    "c2c_invoice_generated_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "c2c_invoice_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Email Sent", "Email Sent"),
                            ("Paid", "Paid"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "c2c_invoice_email_sent_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "c2c_invoice_payment_marked_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "c2c_total_hours_count",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("c2c_resource_count", models.IntegerField(blank=True, null=True)),
                (
                    "c2c_client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "c2c_contract_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="c2c_modules.sow_contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date Updated"
                    ),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("total_billable_hours", models.FloatField(blank=True, null=True)),
                ("total_cost_hours", models.FloatField(blank=True, null=True)),
                ("total_unplanned_hours", models.FloatField(blank=True, null=True)),
                ("allocations_count", models.IntegerField(blank=True, null=True)),
                (
                    "resource_data",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_allocation",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "estimation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimation_allocation",
                        to="c2c_modules.estimation",
                    ),
                ),
                (
                    "contract_sow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractsow_allocation",
                        to="c2c_modules.sow_contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation",
                "verbose_name_plural": "Allocations",
                "unique_together": {("contract_sow", "estimation", "client")},
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billable_hours", models.IntegerField(blank=True, null=True)),
                ("cost_hours", models.IntegerField(blank=True, null=True)),
                (
                    "resource_estimation_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_allocation",
                        to="c2c_modules.allocation",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_client",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "contract_sow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_contractsow",
                        to="c2c_modules.sow_contract",
                    ),
                ),
                (
                    "estimation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_estimation",
                        to="c2c_modules.estimation",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_resource",
                        to="c2c_modules.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UtilizedAmount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "utilized_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "username_created",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "username_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilized_amounts",
                        to="c2c_modules.purchaseorder",
                    ),
                ),
                (
                    "sow_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilized_amounts",
                        to="c2c_modules.sow_contract",
                    ),
                ),
            ],
            options={
                "unique_together": {("sow_contract", "purchase_order")},
            },
        ),
    ]
