# Generated by Django 5.0.2 on 2024-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2c_modules", "0002_profilingresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="estimation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="purchase_order_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="sow_contract",
            name="contractsow_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
