# Generated by Django 5.0.2 on 2024-10-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2c_modules", "0003_alter_client_name_alter_contract_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_invoice_terms",
            field=models.CharField(
                choices=[
                    (None, "Active"),
                    (None, "Inactive"),
                    (None, "Potential Lead"),
                    (None, "ONBOARDED"),
                ],
                default=None,
                max_length=33,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeEntryTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("week_number", models.PositiveIntegerField()),
                ("billable_hours", models.FloatField()),
                ("non_billable_hours", models.FloatField()),
                ("unplanned_hours", models.FloatField()),
                ("total_hours", models.FloatField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_entry_client",
                        to="c2c_modules.client",
                    ),
                ),
                (
                    "contract_sow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_entry_contract_sow",
                        to="c2c_modules.sow_contract",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_entry_id",
                        to="c2c_modules.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("employee_id", "year", "week_number", "client", "contract_sow")
                },
            },
        ),
    ]
