# Generated by Django 5.0.2 on 2024-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2c_modules", "0004_alter_client_client_invoice_terms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_invoice_terms",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("potential lead", "Potential Lead"),
                    ("onboarded", "ONBOARDED"),
                ],
                default="active",
                max_length=33,
            ),
        ),
    ]
