# Generated by Django 5.0.2 on 2024-10-11 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("c2c_modules", "0005_alter_client_client_invoice_terms"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Main_milestone",
            new_name="MainMilestone",
        ),
        migrations.RenameModel(
            old_name="Sow_Contract",
            new_name="SowContract",
        ),
    ]
