# Generated by Django 5.0.2 on 2024-10-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0006_rename_main_milestone_mainmilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='timesheet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_entry_timesheet', to='c2c_modules.timesheet'),
        ),
    ]
