# Generated by Django 5.0.2 on 2024-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0007_employeeentrytimesheet_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeentrytimesheet',
            old_name='comments',
            new_name='non_billable_hours_comments',
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='unplanned_hours_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
