# Generated by Django 5.0.2 on 2024-10-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0008_rename_comments_employeeentrytimesheet_non_billable_hours_comments_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeentrytimesheet',
            unique_together={('employee_id', 'year', 'week_number')},
        ),
        migrations.AlterField(
            model_name='employeeentrytimesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_entry_client', to='c2c_modules.client'),
        ),
        migrations.AlterField(
            model_name='employeeentrytimesheet',
            name='contract_sow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_entry_contract_sow', to='c2c_modules.sowcontract'),
        ),
    ]
