# Generated by Django 5.0.2 on 2024-10-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0009_alter_employeeentrytimesheet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeentrytimesheet',
            unique_together=set(),
        ),
    ]
