# Generated by Django 5.0.2 on 2024-10-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0010_alter_employeeentrytimesheet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_allocation', to='c2c_modules.allocation'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_client', to='c2c_modules.client'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='contract_sow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_contractsow', to='c2c_modules.sowcontract'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_estimation', to='c2c_modules.estimation'),
        ),
    ]
