# Generated by Django 5.0.2 on 2024-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0011_alter_timesheet_allocation_alter_timesheet_client_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeentrytimesheet',
            constraint=models.UniqueConstraint(fields=('employee_id', 'year', 'week_number'), name='unique_employee_week_entry'),
        ),
    ]
