# Generated by Django 5.0.2 on 2024-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0013_remove_employeeentrytimesheet_unique_employee_week_entry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeentrytimesheet',
            name='unique_employee_week_entry',
        ),
        migrations.AddConstraint(
            model_name='employeeentrytimesheet',
            constraint=models.UniqueConstraint(fields=('employee_id', 'year', 'week_number'), name='unique_employee_week_entry'),
        ),
    ]
