# Generated by Django 5.0.2 on 2024-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0014_remove_employeeentrytimesheet_unique_employee_week_entry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeentrytimesheet',
            name='unique_employee_week_entry',
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End_Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Start_Date'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='contract_end_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='End_Date'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='contract_start_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Start_Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='end_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='End_Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='start_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Start_Date'),
        ),
        migrations.AlterField(
            model_name='sowcontract',
            name='end_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='End_Date'),
        ),
        migrations.AlterField(
            model_name='sowcontract',
            name='start_date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Start_Date'),
        ),
    ]
