# Generated by Django 5.0.2 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0015_remove_employeeentrytimesheet_unique_employee_week_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillpayrate',
            name='experience',
            field=models.CharField(default='Assign Experience', max_length=100),
        ),
    ]
