# Generated by Django 5.0.2 on 2024-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0016_skillpayrate_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='employee_account_type',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='assigned_role',
            new_name='employee_assigned_role',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='country',
            new_name='employee_category',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emptype_category',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='workauthorization',
            new_name='employee_designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email_id',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='employee_full_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ceipal_id',
            new_name='employee_source_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill_details',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_reporting_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_skills',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_work_authorization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
