# Generated by Django 5.0.2 on 2024-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0017_rename_department_employee_employee_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_source_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
