# Generated by Django 5.0.2 on 2024-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0018_alter_employee_employee_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_assigned_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_reporting_manager',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
