# Generated by Django 5.0.2 on 2024-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0019_alter_employee_employee_assigned_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
