# Generated by Django 5.0.2 on 2024-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0020_alter_employee_employee_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='utilizedamount',
            name='utilized_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
