# Generated by Django 5.0.2 on 2024-12-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0021_alter_purchaseorder_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUnplannedNonbillableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveIntegerField()),
                ('non_billable_hours', models.FloatField()),
                ('unplanned_hours', models.FloatField()),
                ('non_billable_hours_comments', models.TextField(blank=True, null=True)),
                ('unplanned_hours_comments', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_unplanned_non_billable_entry_id', to='c2c_modules.employee')),
                ('timesheet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_unplanned_non_billable_timesheet', to='c2c_modules.timesheet')),
            ],
        ),
    ]
