# Generated by Django 5.0.2 on 2024-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0023_remove_employeeunplannednonbillablehours_timesheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowcontract',
            name='extension_sow_contract',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
