# Generated by Django 5.0.2 on 2024-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0024_sowcontract_extension_sow_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
