# Generated by Django 5.0.2 on 2024-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0025_client_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowcontract',
            name='extension_sow_contract',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
