# Generated by Django 5.0.2 on 2025-01-06 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0026_alter_sowcontract_extension_sow_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('guest_user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('guest_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_user_email_id', models.EmailField(max_length=254, unique=True)),
                ('client_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('guest_user_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='approver',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='approver',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='approver_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='ts_approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('not submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('recall', 'Recall')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeunplannednonbillablehours',
            name='approver',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='employeeunplannednonbillablehours',
            name='approver_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeunplannednonbillablehours',
            name='ts_approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('not submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('recall', 'Recall')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approver',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
