# Generated by Django 5.0.2 on 2025-01-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0027_guestuser_allocation_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='employeeentrytimesheet',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='employeeunplannednonbillablehours',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='client_ids',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='approver',
        ),
    ]
