# Generated by Django 5.0.2 on 2025-01-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0028_remove_allocation_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='approver',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='employeeentrytimesheet',
            name='approver',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='employeeunplannednonbillablehours',
            name='approver',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='client_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approver',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
