# Generated by Django 5.0.2 on 2025-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0029_allocation_approver_employeeentrytimesheet_approver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2CRateCardConfig',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('dollar_conversion_rate', models.FloatField(help_text='Conversion rate (e.g., 84 INR/USD)')),
                ('overhead_percentage', models.FloatField(help_text='Overhead percentage (e.g., 20%)')),
                ('non_billable_days_per_year', models.IntegerField(help_text='Non-billable days per year (e.g., 20)')),
                ('desired_gross_margin_percentage', models.FloatField(help_text='Desired Gross Margin percentage (e.g., 30%)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Updated')),
                ('username_created', models.CharField(blank=True, max_length=255, null=True)),
                ('username_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
