# Generated by Django 5.0.2 on 2025-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0030_c2cratecardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='desired_gross_margin_percentage_usa',
            field=models.FloatField(default=20, help_text='Desired Gross Margin percentage (e.g., 25%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='non_billable_days_per_year_usa',
            field=models.IntegerField(default=20, help_text='Non-billable days per year (e.g., 12)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='overhead_percentage_usa',
            field=models.FloatField(default=20, help_text='Overhead percentage (e.g., 20%)'),
            preserve_default=False,
        ),
    ]
