# Generated by Django 5.0.2 on 2025-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0032_remove_c2cratecardconfig_desired_gross_margin_percentage_usa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='desired_gross_margin_percentage_usa',
            field=models.FloatField(default=20, help_text='Desired Gross Margin percentage (e.g., 30%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='non_billable_days_per_year_usa',
            field=models.IntegerField(default=12, help_text='Non-billable days per year (e.g., 20)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='overhead_percentage_usa',
            field=models.FloatField(default=25, help_text='Overhead percentage (e.g., 20%)'),
            preserve_default=False,
        ),
    ]
