# Generated by Django 5.0.2 on 2025-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0035_employeeentrytimesheet_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_joined_date',
            field=models.CharField(blank=True, default='01-01-2025', null=True),
        ),
    ]
