# Generated by Django 5.0.2 on 2025-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0036_employee_employee_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='minimum_sell_rate',
            field=models.FloatField(default=20.0, help_text='Minimum sell rate (e.g., 20.00)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c2cratecardconfig',
            name='minimum_sellrate_usa',
            field=models.FloatField(default=20.0, help_text='Minimum sell rate in USA (e.g., 20.00)'),
            preserve_default=False,
        ),
    ]
