# Generated by Django 5.0.2 on 2025-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c_modules', '0037_c2cratecardconfig_minimum_sell_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeunplannednonbillablehours',
            name='non_billable_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeunplannednonbillablehours',
            name='unplanned_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
