name: Create Azure PostgreSQL Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
  push:
    branches:
      - db-env-test

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: db-env-test

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: terraform
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Set outputs
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        id: outputs
        run: |
          terraform output -json > outputs.json
          echo "DB_HOSTNAME=$(jq -r '.DB_HOSTNAME.value' outputs.json)" >> $GITHUB_ENV
          echo "DB_USERNAME=$(jq -r '.DB_USERNAME.value' outputs.json)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(jq -r '.DB_PASSWORD.value' outputs.json)" >> $GITHUB_ENV
          echo "DB_NAME=$(jq -r '.DB_NAME.value' outputs.json)" >> $GITHUB_ENV
          echo "DB_PORT=$(jq -r '.DB_PORT.value' outputs.json)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Upload outputs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-outputs
          path: terraform/outputs.json