name: Create Azure PostgreSQL Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
  push:
    branches:
      - db-env-test

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: db-env-test

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: |
          terraform apply -auto-approve
          terraform output -json > terraform_output.json
        working-directory: terraform
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Parse and Set Secrets
        run: |
          DB_HOSTNAME=$(jq -r '.DB_HOSTNAME.value' terraform/terraform_output.json)
          DB_USERNAME=$(jq -r '.DB_USERNAME.value' terraform/terraform_output.json)
          DB_PASSWORD=$(jq -r '.DB_PASSWORD.value' terraform/terraform_output.json)
          DB_NAME=$(jq -r '.DB_NAME.value' terraform/terraform_output.json)
          DB_PORT=$(jq -r '.DB_PORT.value' terraform/terraform_output.json)
          gh secret set DB_HOSTNAME --body "$DB_HOSTNAME"
          gh secret set DB_USERNAME --body "$DB_USERNAME"
          gh secret set DB_PASSWORD --body "$DB_PASSWORD"
          gh secret set DB_NAME --body "$DB_NAME"
          gh secret set DB_PORT --body "$DB_PORT"
        working-directory: terraform