name: Create Azure PostgreSQL Database

on: [push]

jobs:
  create-db:
    runs-on: ubuntu-latest
    outputs:
      db-hostname: ${{ steps.outputs.outputs.db-hostname }}
      db-username: ${{ steps.outputs.outputs.db-username }}
      db-password: ${{ steps.outputs.outputs.db-password }}
      db-name: ${{ steps.outputs.outputs.db-name }}
      db-port: ${{ steps.outputs.outputs.db-port }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Set outputs
        id: outputs
        run: |
          echo "::set-output name=db-hostname::$(terraform output -raw DB_HOSTNAME)"
          echo "::set-output name=db-username::$(terraform output -raw DB_USERNAME)"
          echo "::set-output name=db-password::$(terraform output -raw DB_PASSWORD)"
          echo "::set-output name=db-name::$(terraform output -raw DB_NAME)"
          echo "::set-output name=db-port::$(terraform output -raw DB_PORT)"